# Generated by Django 2.1.3 on 2019-01-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_type', models.CharField(choices=[('first_course', 'Первое блюдо'), ('snacks', 'Закуски'), ('salad', 'Салат'), ('dessert', 'Десерт')], max_length=50)),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'ordering': ('dish_name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('ingredient_name',),
            },
        ),
        migrations.AddField(
            model_name='dishmodel',
            name='ingredients',
            field=models.ManyToManyField(to='randish_models.Ingredients'),
        ),
    ]
