# Generated by Django 2.1.3 on 2019-01-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0002_auto_20190103_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='image',
            field=models.ImageField(upload_to='static/image', verbose_name='Картинка'),
        ),
    ]
