# Generated by Django 2.1.3 on 2019-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0003_auto_20190103_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='dish_type',
            field=models.CharField(choices=[('Первое блюдо', 'Первое блюдо'), ('Закуски', 'Закуски'), ('Салат', 'Салат'), ('Десерт', 'Десерт')], max_length=50, verbose_name='Тип блюда'),
        ),
    ]
