# Generated by Django 2.1.3 on 2019-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0004_auto_20190103_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='dish_type',
            field=models.CharField(choices=[('Салаты', 'Салаты'), ('Закуски', 'Закуски'), ('Первые блюда', 'Первые блюда'), ('Гарниры', 'Гарниры'), ('Соусы и подливы', 'Соусы и подливы'), ('Десерты', 'Десерты'), ('Выпечка', 'Выпечка'), ('Напитки', 'Напитки'), ('Консервирование', 'Консервирование')], max_length=50, verbose_name='Тип блюда'),
        ),
    ]
