# Generated by Django 2.1.3 on 2019-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0007_auto_20190108_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='dish_type',
            field=models.CharField(choices=[('Салаты', 'Салаты'), ('Закуски', 'Закуски'), ('Первые блюда', 'Первые блюда'), ('Основные блюда', 'Основные блюда'), ('Гарниры', 'Гарниры'), ('Соусы и подливы', 'Соусы и подливы'), ('Десерты', 'Десерты'), ('Выпечка', 'Выпечка'), ('доп_Напитки', 'Напитки'), ('доп_Консервирование', 'Консервирование')], max_length=50, verbose_name='Тип блюда'),
        ),
    ]
