# Generated by Django 2.1.3 on 2019-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0009_auto_20190108_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='dish_type',
            field=models.CharField(choices=[('Салаты', 'Салаты'), ('Закуски', 'Закуски'), ('Первые блюда', 'Первые блюда'), ('Основные блюда', 'Основные блюда'), ('Гарниры', 'Гарниры'), ('Соусы и подливы', 'Соусы и подливы'), ('Десерты', 'Десерты'), ('Выпечка', 'Выпечка'), ('Напитки', 'Напитки'), ('Консервирование', 'Консервирование')], max_length=50, verbose_name='Тип блюда'),
        ),
        migrations.AlterField(
            model_name='dishmodel',
            name='image',
            field=models.ImageField(upload_to='static/randish/image', verbose_name='Картинка'),
        ),
    ]
