# Generated by Django 2.1.3 on 2019-01-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0010_auto_20190111_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='image',
            field=models.FileField(upload_to='static/randish/image', verbose_name='Картинка'),
        ),
    ]
