# Generated by Django 2.1.3 on 2019-01-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0011_auto_20190117_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='image',
            field=models.ImageField(upload_to='static/randish/image', verbose_name='Картинка'),
        ),
    ]
