# Generated by Django 2.1.3 on 2019-02-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0014_auto_20190205_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
