# Generated by Django 2.1.3 on 2019-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0015_auto_20190205_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Картинка'),
        ),
    ]
