# Generated by Django 2.1.3 on 2019-03-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0016_auto_20190306_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
