# Generated by Django 2.1.3 on 2019-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randish_models', '0017_auto_20190306_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmodel',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='Картинка'),
        ),
    ]
